name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install backend dependency
        run: |
          cd backend
          npm install

      - name: Install frontend dependency
        run: |
          cd frontend
          npm install

      - name: Build docker images
        run: |
          cd backend
          docker build -t my-ytclone .
          cd ../frontend
          docker build -t frontend-yt .
